[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "opteryx-app"
version = "0.0.0"
description = "Opteryx Data API"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.101.0",
    "opteryx==0.26.1",
    "uvicorn[standard]==0.23.2",
]
