[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "opteryx-worker"
version = "0.0.0"
description = "Opteryx Worker service"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.101.0",
    "uvicorn[standard]==0.23.2",
    "pydantic==2.12.4",
    "opteryx==0.26.1"
]
